/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autopressbot;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
/**
 *
 * @author chris
 */
public class JFrameBot extends javax.swing.JFrame{

    private AutoPressBot bot;

    public JFrameBot(long tIte, long tFunc, long tIni, boolean isKey, int keyCode) {
        bot = new AutoPressBot();
        bot.setTiempoIteracion(tIte);
        bot.setTiempoDeFuncion(tFunc);
        bot.setTiempoParaIniciar(tIni);
        bot.setIsKey(isKey);
        bot.setKeyCode(keyCode);
        bot.setJfBot(this);
        initComponents();
        Image iconoPropio = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/autopressbot/data/icono.png"));
        setIconImage(iconoPropio);
        setLocationRelativeTo(null);
        jProgressBarBot.setMinimum(0);
        jProgressBarBot.setMaximum((int)(tFunc/tIte));
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTituloBot = new javax.swing.JLabel();
        jlblIteraciones = new javax.swing.JLabel();
        jlblTiempoRestante = new javax.swing.JLabel();
        jlblImagenPicoDiamante = new javax.swing.JLabel();
        jlblTrabajando = new javax.swing.JLabel();
        jProgressBarBot = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jlblTituloBot.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlblTituloBot.setText("Bot");

        jlblIteraciones.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblIteraciones.setText("Iteraciones: ");

        jlblTiempoRestante.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblTiempoRestante.setText("Iteraciones restantes: ");

        jlblImagenPicoDiamante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autopressbot/data/Pico_de_diamante_encantado.gif"))); // NOI18N

        jlblTrabajando.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jlblTrabajando.setText("Iniciándose...");

        jProgressBarBot.setForeground(new java.awt.Color(0, 204, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblIteraciones)
                    .addComponent(jlblTiempoRestante))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jProgressBarBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlblTrabajando)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblImagenPicoDiamante)
                                .addGap(14, 14, 14)))
                        .addGap(95, 95, 95))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblTituloBot)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTituloBot)
                .addGap(41, 41, 41)
                .addComponent(jlblIteraciones)
                .addGap(30, 30, 30)
                .addComponent(jlblTiempoRestante)
                .addGap(40, 40, 40)
                .addComponent(jlblImagenPicoDiamante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblTrabajando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jProgressBarBot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        long ni = bot.getNumeroIteraciones();
        bot.setContadorInteraciones(ni);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    public AutoPressBot getBot() {
        return bot;
    }

    public void setBot(AutoPressBot bot) {
        this.bot = bot;
    }

    public JLabel getJlblIteraciones() {
        return jlblIteraciones;
    }

    public void setJlblIteraciones(JLabel jlblIteraciones) {
        this.jlblIteraciones = jlblIteraciones;
    }

    public JLabel getJlblTiempoRestante() {
        return jlblTiempoRestante;
    }

    public void setJlblTiempoRestante(JLabel jlblTiempoRestante) {
        this.jlblTiempoRestante = jlblTiempoRestante;
    }

    public JLabel getJlblTituloBot() {
        return jlblTituloBot;
    }

    public void setJlblTituloBot(JLabel jlblTituloBot) {
        this.jlblTituloBot = jlblTituloBot;
    }

    public JProgressBar getjProgressBarBot() {
        return jProgressBarBot;
    }

    public void setjProgressBarBot(JProgressBar jProgressBarBot) {
        this.jProgressBarBot = jProgressBarBot;
    }

    public JLabel getJlblTrabajando() {
        return jlblTrabajando;
    }

    public void setJlblTrabajando(JLabel jlblTrabajando) {
        this.jlblTrabajando = jlblTrabajando;
    }

    public JLabel getJlblImagenPicoDiamante() {
        return jlblImagenPicoDiamante;
    }

    public void setJlblImagenPicoDiamante(JLabel jlblImagenPicoDiamante) {
        this.jlblImagenPicoDiamante = jlblImagenPicoDiamante;
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBarBot;
    private javax.swing.JLabel jlblImagenPicoDiamante;
    private javax.swing.JLabel jlblIteraciones;
    private javax.swing.JLabel jlblTiempoRestante;
    private javax.swing.JLabel jlblTituloBot;
    private javax.swing.JLabel jlblTrabajando;
    // End of variables declaration//GEN-END:variables
}
