/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autopressbot;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author chris
 */
public class JFrameInicio extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public JFrameInicio() {
        initComponents();
        Image iconoPropio = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/autopressbot/data/icono.png"));
        setIconImage(iconoPropio);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblTitulo = new javax.swing.JLabel();
        jlblTiempoIteracion = new javax.swing.JLabel();
        jtfTiempoIteracion = new javax.swing.JTextField();
        jlblTiempoDeFuncion = new javax.swing.JLabel();
        jlblTiempoParaIniciar = new javax.swing.JLabel();
        jtfTiempoDeFuncion = new javax.swing.JTextField();
        jtfTiempoParaIniciar = new javax.swing.JTextField();
        jbtnIniciarBot = new javax.swing.JButton();
        jlblInfoParametros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jlblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitulo.setText("Ingresar parametros");

        jlblTiempoIteracion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblTiempoIteracion.setText("Tiempo por iteración:");

        jtfTiempoIteracion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfTiempoIteracion.setText("1");

        jlblTiempoDeFuncion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblTiempoDeFuncion.setText("Tiempo de función:");

        jlblTiempoParaIniciar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblTiempoParaIniciar.setText("Tiempo antes de iniciar:");

        jtfTiempoDeFuncion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfTiempoDeFuncion.setText("3600");

        jtfTiempoParaIniciar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfTiempoParaIniciar.setText("10");

        jbtnIniciarBot.setBackground(new java.awt.Color(102, 204, 255));
        jbtnIniciarBot.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtnIniciarBot.setText("Iniciar Bot");
        jbtnIniciarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIniciarBotActionPerformed(evt);
            }
        });

        jlblInfoParametros.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jlblInfoParametros.setText("(Tiempo en Segundos)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblTiempoDeFuncion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfTiempoDeFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblTiempoParaIniciar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfTiempoParaIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblTiempoIteracion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblInfoParametros)
                                    .addComponent(jtfTiempoIteracion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jlblTitulo)
                                .addGap(89, 89, 89))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jbtnIniciarBot)
                                .addContainerGap())))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblInfoParametros)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTiempoIteracion)
                    .addComponent(jtfTiempoIteracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTiempoDeFuncion)
                    .addComponent(jtfTiempoDeFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTiempoParaIniciar)
                    .addComponent(jtfTiempoParaIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jbtnIniciarBot)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIniciarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIniciarBotActionPerformed
        long tIteracion = Long.parseLong(jtfTiempoIteracion.getText());
        long tFuncion = Long.parseLong(jtfTiempoDeFuncion.getText());
        long tIniciacion = Long.parseLong(jtfTiempoParaIniciar.getText());
        JFrameBot jfBot = new JFrameBot(tIteracion, tFuncion, tIniciacion);
        Thread t = jfBot.getBot();
        t.start();
    }//GEN-LAST:event_jbtnIniciarBotActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnIniciarBot;
    private javax.swing.JLabel jlblInfoParametros;
    private javax.swing.JLabel jlblTiempoDeFuncion;
    private javax.swing.JLabel jlblTiempoIteracion;
    private javax.swing.JLabel jlblTiempoParaIniciar;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JTextField jtfTiempoDeFuncion;
    private javax.swing.JTextField jtfTiempoIteracion;
    private javax.swing.JTextField jtfTiempoParaIniciar;
    // End of variables declaration//GEN-END:variables

}
