/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autopressbot;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author chris
 */
public class JFrameInicio extends javax.swing.JFrame {

    private boolean isKey=true;
    private int keyCode;
    public JFrameInicio() {
        initComponents();
        Image iconoPropio = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/autopressbot/data/icono.png"));
        setIconImage(iconoPropio);
        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jframeEleccionTecla = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jlblTitulo = new javax.swing.JLabel();
        jlblTiempoIteracion = new javax.swing.JLabel();
        jtfTiempoIteracion = new javax.swing.JTextField();
        jlblTiempoDeFuncion = new javax.swing.JLabel();
        jlblTiempoParaIniciar = new javax.swing.JLabel();
        jtfTiempoDeFuncion = new javax.swing.JTextField();
        jtfTiempoParaIniciar = new javax.swing.JTextField();
        jbtnIniciarBot = new javax.swing.JButton();
        jlblInfoParametros = new javax.swing.JLabel();
        jbtnTecla = new javax.swing.JButton();
        jlblElegirTeclaOMouse = new javax.swing.JLabel();
        jcbMovMouseEntreIteracion = new javax.swing.JCheckBox();
        jcbApagarAlFinalizar = new javax.swing.JCheckBox();

        jframeEleccionTecla.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jframeEleccionTecla.setResizable(false);
        jframeEleccionTecla.setSize(new java.awt.Dimension(300, 300));
        jframeEleccionTecla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jframeEleccionTeclaMouseClicked(evt);
            }
        });
        jframeEleccionTecla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jframeEleccionTeclaKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Presionar tecla o mouse");

        javax.swing.GroupLayout jframeEleccionTeclaLayout = new javax.swing.GroupLayout(jframeEleccionTecla.getContentPane());
        jframeEleccionTecla.getContentPane().setLayout(jframeEleccionTeclaLayout);
        jframeEleccionTeclaLayout.setHorizontalGroup(
            jframeEleccionTeclaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframeEleccionTeclaLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jLabel1)
                .addContainerGap(68, Short.MAX_VALUE))
        );
        jframeEleccionTeclaLayout.setVerticalGroup(
            jframeEleccionTeclaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframeEleccionTeclaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jlblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jlblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitulo.setText("Ingresar parametros");

        jlblTiempoIteracion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblTiempoIteracion.setText("Tiempo por iteración:");

        jtfTiempoIteracion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfTiempoIteracion.setText("1");

        jlblTiempoDeFuncion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblTiempoDeFuncion.setText("Tiempo de función:");

        jlblTiempoParaIniciar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblTiempoParaIniciar.setText("Tiempo antes de iniciar:");

        jtfTiempoDeFuncion.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfTiempoDeFuncion.setText("3600");

        jtfTiempoParaIniciar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jtfTiempoParaIniciar.setText("10");

        jbtnIniciarBot.setBackground(new java.awt.Color(102, 204, 255));
        jbtnIniciarBot.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jbtnIniciarBot.setText("Iniciar Bot");
        jbtnIniciarBot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIniciarBotActionPerformed(evt);
            }
        });

        jlblInfoParametros.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jlblInfoParametros.setText("(Tiempo en Segundos)");

        jbtnTecla.setBackground(new java.awt.Color(204, 204, 204));
        jbtnTecla.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jbtnTecla.setText("Elegir");
        jbtnTecla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTeclaActionPerformed(evt);
            }
        });

        jlblElegirTeclaOMouse.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlblElegirTeclaOMouse.setText("Elegir tecla o mouse:");

        jcbMovMouseEntreIteracion.setText("Mover mouse cada iteracion");

        jcbApagarAlFinalizar.setText("Apagar al finalizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlblElegirTeclaOMouse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblTiempoDeFuncion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfTiempoDeFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblTiempoIteracion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlblInfoParametros)
                                    .addComponent(jtfTiempoIteracion, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jlblTiempoParaIniciar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtfTiempoParaIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 71, Short.MAX_VALUE)
                        .addComponent(jlblTitulo)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtnTecla)
                            .addComponent(jcbApagarAlFinalizar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtnIniciarBot)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcbMovMouseEntreIteracion)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlblInfoParametros)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTiempoIteracion)
                    .addComponent(jtfTiempoIteracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTiempoDeFuncion)
                    .addComponent(jtfTiempoDeFuncion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTiempoParaIniciar)
                    .addComponent(jtfTiempoParaIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlblElegirTeclaOMouse, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnTecla)
                .addGap(18, 18, 18)
                .addComponent(jcbMovMouseEntreIteracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnIniciarBot)
                    .addComponent(jcbApagarAlFinalizar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnIniciarBotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIniciarBotActionPerformed
        long tIteracion = Long.parseLong(jtfTiempoIteracion.getText());
        long tFuncion = Long.parseLong(jtfTiempoDeFuncion.getText());
        long tIniciacion = Long.parseLong(jtfTiempoParaIniciar.getText());
        boolean hasMov = jcbMovMouseEntreIteracion.isSelected();
        boolean apagar = jcbApagarAlFinalizar.isSelected();
        JFrameBot jfBot = new JFrameBot(tIteracion, tFuncion, tIniciacion, isKey, keyCode, hasMov, apagar);
        Thread t = jfBot.getBot();
        t.start();
    }//GEN-LAST:event_jbtnIniciarBotActionPerformed

    private void jframeEleccionTeclaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jframeEleccionTeclaKeyPressed
        jlblElegirTeclaOMouse.setText("Tecla elegida: " + evt.getKeyChar() + " Code: " + evt.getKeyCode());
        keyCode = evt.getKeyCode();
        isKey=true;
        jframeEleccionTecla.dispose();
    }//GEN-LAST:event_jframeEleccionTeclaKeyPressed

    private void jbtnTeclaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTeclaActionPerformed
        jframeEleccionTecla.setLocationRelativeTo(null);
        jframeEleccionTecla.setVisible(true);
        
    }//GEN-LAST:event_jbtnTeclaActionPerformed

    private void jframeEleccionTeclaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jframeEleccionTeclaMouseClicked
        jlblElegirTeclaOMouse.setText("Accion del mouse elegida: " + evt.getModifiers());
        keyCode = evt.getModifiers();
        isKey=false;
        jframeEleccionTecla.dispose();
    }//GEN-LAST:event_jframeEleccionTeclaMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnIniciarBot;
    private javax.swing.JButton jbtnTecla;
    private javax.swing.JCheckBox jcbApagarAlFinalizar;
    private javax.swing.JCheckBox jcbMovMouseEntreIteracion;
    private javax.swing.JFrame jframeEleccionTecla;
    private javax.swing.JLabel jlblElegirTeclaOMouse;
    private javax.swing.JLabel jlblInfoParametros;
    private javax.swing.JLabel jlblTiempoDeFuncion;
    private javax.swing.JLabel jlblTiempoIteracion;
    private javax.swing.JLabel jlblTiempoParaIniciar;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JTextField jtfTiempoDeFuncion;
    private javax.swing.JTextField jtfTiempoIteracion;
    private javax.swing.JTextField jtfTiempoParaIniciar;
    // End of variables declaration//GEN-END:variables

}
